### ISSUE TITLE
"IOC Fanger" Package to "Fang" and "Defang" Network Data

### ISSUE THREAD

**Issue by fhightower** [bschmoker/defang-me#1]
Hi @bschmoker : I've been working on a package to "fang" and "defang" network data here: https://github.com/ioc-fang/ioc_fanger. You may want to take a look at it as it may help your use-case. Any feedback/issues are appreciated.

Feel free to close this issue; I just wanted to mention the "IOC Fanger" as it may be helpful for what you are doing.

**Comment by bschmoker** [comment]
Very cool! I sent you a message via your site

**Comment by fhightower** [comment]
Thanks! Sorry it's taken me so long to get back to you (been offline), but I'll respond shortly.
